name: release
on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-24.04
    name: Create release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag
        id: get-tag
        uses: devops-actions/action-get-tag@v1.0.3
        with:
          strip_v: false # Optional: Remove 'v' character from version
          default: v0.0.0 # Optional: Default version when tag not foun

      - name: Create release
        run: |
          gh release create ${{ steps.get-tag.outputs.tag }} \
            --draft \
            --verify-tag \
            --title ${{ steps.get-tag.outputs.tag }}

  build-release:
    runs-on: ubuntu-24.04
    name: Release
    needs:
      - create-release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: true
      matrix:
        arch: ["arm64", "amd64"]
        os: ["linux", "darwin"]
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get tag
        id: get-tag
        uses: devops-actions/action-get-tag@v1.0.3
        with:
          strip_v: false # Optional: Remove 'v' character from version
          default: v0.0.0 # Optional: Default version when tag not foun
      
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      
      - name: Build binary app
        run: |
          cd backend-app
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o backend-app_${{ steps.get-tag.outputs.tag }}_${{ matrix.os }}_${{ matrix.arch }} .
          cd ..
          cd edge-app
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o edge-app_${{ steps.get-tag.outputs.tag }}_${{ matrix.os }}_${{ matrix.arch }} .
      
      - name: Upload release
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          gh release upload ${{ steps.get-tag.outputs.tag }} \
            backend-app/backend-app_${{ steps.get-tag.outputs.tag }}_${{ matrix.os }}_${{ matrix.arch }} \
            edge-app/edge-app_${{ steps.get-tag.outputs.tag }}_${{ matrix.os }}_${{ matrix.arch }}
  
  publish-release:
    runs-on: ubuntu-24.04
    name: Publish release
    needs:
      - build-release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag
        id: get-tag
        uses: devops-actions/action-get-tag@v1.0.3
        with:
          strip_v: false # Optional: Remove 'v' character from version
          default: v0.0.0 # Optional: Default version when tag not foun

      - name: Publish release
        run: |
          gh release edit ${{ steps.get-tag.outputs.tag }} \
            --draft=false